sudo: required
services:
    - docker
    
    
before_install:
    - docker build -t docker19995/docker-react -f Dockerfile.dev .
    
script:
    - docker run -e CI=true docker19995/docker-react npm run test -- --coverage